/*subfolder
*  This file is part of openauto project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  openauto is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  openauto is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with openauto. If not, see <http://www.gnu.org/licenses/>.
*/
#include <fstream>
#include <string>
#include <f1x/openauto/autoapp/UI/SettingsWindow.hpp>
#include <QBluetoothLocalDevice>
#include <QBluetoothHostInfo>
#include <QComboBox>
#include <QCoreApplication>
#include <QDateTime>
#include <QDBusInterface>
#include <QDBusReply>
#include <QFile>
#include <QFileInfo>
#include <QMessageBox>
#include <QNetworkInterface>
#include <QProcess>
#include <QStorageInfo>
#include <QTextStream>
#include <QTimer>
#include "ui_settingswindow.h"  // AutoGenerated at Compile Time

#ifdef MAC_OS

#include <mach/mach_host.h>
#include <mach/mach_init.h>
#include <mach/mach_port.h>
#include <mach/vm_map.h>
#include <mach/vm_statistics.h>
#include <mach/mach_types.h>

#endif


namespace f1x::openauto::autoapp::ui {

  SettingsWindow::SettingsWindow(configuration::IConfiguration::Pointer configuration, QWidget *parent)
      : QWidget(parent), ui_(new Ui::SettingsWindow), configuration_(std::move(configuration)) {
    ui_->setupUi(this);
    connect(ui_->pushButtonCancel, &QPushButton::clicked, this, &SettingsWindow::close);
    connect(ui_->pushButtonSave, &QPushButton::clicked, this, &SettingsWindow::onSave);
    connect(ui_->pushButtonUnpair, &QPushButton::clicked, this, &SettingsWindow::unpairAll);
    connect(ui_->pushButtonUnpair, &QPushButton::clicked, this, &SettingsWindow::close);
    connect(ui_->horizontalSliderScreenDPI, &QSlider::valueChanged, this, &SettingsWindow::onUpdateScreenDPI);
    connect(ui_->horizontalSliderAlphaTrans, &QSlider::valueChanged, this, &SettingsWindow::onUpdateAlphaTrans);
    connect(ui_->horizontalSliderDay, &QSlider::valueChanged, this, &SettingsWindow::onUpdateBrightnessDay);
    connect(ui_->horizontalSliderNight, &QSlider::valueChanged, this, &SettingsWindow::onUpdateBrightnessNight);

    connect(ui_->pushButtonClearSelection, &QPushButton::clicked,
            std::bind(&SettingsWindow::setButtonCheckBoxes, this, false));
    connect(ui_->pushButtonSelectAll, &QPushButton::clicked,
            std::bind(&SettingsWindow::setButtonCheckBoxes, this, true));
    connect(ui_->pushButtonResetToDefaults, &QPushButton::clicked, this, &SettingsWindow::onResetToDefaults);
    connect(ui_->horizontalSliderSystemVolume, &QSlider::valueChanged, this,
            &SettingsWindow::onUpdateSystemVolume);
    connect(ui_->horizontalSliderSystemCapture, &QSlider::valueChanged, this,
            &SettingsWindow::onUpdateSystemCapture);
    connect(ui_->radioButtonHotspot, &QPushButton::clicked, this, &SettingsWindow::onStartHotspot);
    connect(ui_->radioButtonClient, &QPushButton::clicked, this, &SettingsWindow::onStopHotspot);
    connect(ui_->pushButtonNetworkAuto, &QPushButton::clicked,
            [&]() { system("/usr/local/bin/crankshaft network auto &"); });
    connect(ui_->pushButtonNetwork0, &QPushButton::clicked, this, &SettingsWindow::on_pushButtonNetwork0_clicked);
    connect(ui_->pushButtonNetwork1, &QPushButton::clicked, this, &SettingsWindow::on_pushButtonNetwork1_clicked);
    connect(ui_->pushButtonSambaStart, &QPushButton::clicked,
            [&]() { system("/usr/local/bin/crankshaft samba start &"); });
    connect(ui_->pushButtonSambaStop, &QPushButton::clicked,
            [&]() { system("/usr/local/bin/crankshaft samba stop &"); });

    // menu
    ui_->tab1->show();
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();


    ui_->labelTestInProgress->hide();

    connect(ui_->pushButtonTab1, &QPushButton::clicked, this, &SettingsWindow::show_tab1);
    connect(ui_->pushButtonTab2, &QPushButton::clicked, this, &SettingsWindow::show_tab2);
    connect(ui_->pushButtonTab3, &QPushButton::clicked, this, &SettingsWindow::show_tab3);
    connect(ui_->pushButtonTab4, &QPushButton::clicked, this, &SettingsWindow::show_tab4);
    connect(ui_->pushButtonTab5, &QPushButton::clicked, this, &SettingsWindow::show_tab5);
    connect(ui_->pushButtonTab5, &QPushButton::clicked, this, &SettingsWindow::updateNetworkInfo);

    ui_->label_modeswitchprogress->setText("Ok");
    ui_->label_notavailable->hide();

    QString wifi_ssid = configuration_->getCSValue("WIFI_SSID");
    QString wifi2_ssid = configuration_->getCSValue("WIFI2_SSID");

    ui_->pushButtonNetwork0->setText(wifi_ssid);
    ui_->pushButtonNetwork1->setText(wifi2_ssid);

    if (!std::ifstream("/boot/crankshaft/network1.conf")) {
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetwork0->show();
    }
    if (!std::ifstream("/boot/crankshaft/network0.conf")) {
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetwork0->setText(configuration_->getCSValue("WIFI2_SSID"));
    }
    if (!std::ifstream("/boot/crankshaft/network0.conf") && !std::ifstream("/boot/crankshaft/network1.conf")) {
      ui_->pushButtonNetwork0->hide();
      ui_->pushButtonNetwork1->hide();
      ui_->pushButtonNetworkAuto->hide();
      ui_->label_notavailable->show();
    }

    if (std::ifstream("/tmp/hotspot_active")) {
      ui_->radioButtonClient->setChecked(0);
      ui_->radioButtonHotspot->setChecked(1);
      ui_->lineEditWifiSSID->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "ssid"));
      ui_->lineEditPassword->show();
      ui_->label_password->show();
      ui_->lineEditPassword->setText("1234567890");
      ui_->clientNetworkSelect->hide();
      ui_->label_notavailable->show();
    } else {
      ui_->radioButtonClient->setChecked(1);
      ui_->radioButtonHotspot->setChecked(0);
      ui_->lineEditWifiSSID->setText(configuration_->readFileContent("/tmp/wifi_ssid"));
      ui_->lineEditPassword->hide();
      ui_->label_password->hide();
      ui_->lineEditPassword->setText("");
      ui_->clientNetworkSelect->hide();
      ui_->label_notavailable->show();
    }

    if (std::ifstream("/tmp/samba_running")) {
      ui_->labelSambaStatus->setText("running");
      ui_->pushButtonSambaStart->hide();
      ui_->pushButtonSambaStop->show();
    } else {
      ui_->labelSambaStatus->setText("stopped");
      ui_->pushButtonSambaStop->hide();
      ui_->pushButtonSambaStart->show();
    }

    QTimer *refresh = new QTimer(this);
    connect(refresh, SIGNAL(timeout()), this, SLOT(updateInfo()));
    refresh->start(5000);
  }

  SettingsWindow::~SettingsWindow() {
    delete ui_;
  }

#ifdef Q_OS_LINUX
  void SettingsWindow::populateBluetoothComboBoxLinux(QComboBox *comboBoxBluetooth) {
    QList<QBluetoothHostInfo> adapters = QBluetoothLocalDevice::allDevices();

    qDebug() << "Found" << adapters.count() << "Bluetooth adapters:";
    // Iterate over the adapters and print their information.
    comboBoxBluetooth->clear(); // Clear existing items

    if (!adapters.isEmpty()) {
      for (const QBluetoothHostInfo &adapter: adapters) {
        QString adapterAddress = adapter.address().toString();
        comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow",
                                                            QString("%1 (%2)").arg(adapter.name()).arg(
                                                                adapterAddress).toUtf8().constData()),
                                                 QVariant(adapterAddress));
      }
    } else {
      comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", "none", nullptr));
    }
  }
#endif
#ifdef Q_OS_WIN
  void SettingsWindow::populateBluetoothComboBoxWindows(QComboBox *comboBoxBluetooth) {
    QProcess process;
    process.start("wmic",
                  QStringList() << "path" << "Win32_PnPEntity" << "where" << "\"PNPDeviceID like '%BTHENUM%'\"" << "get"
                                << "Name,PNPDeviceID");
    process.waitForFinished(-1);

    QString output = process.readAllStandardOutput();
    QStringList lines = output.split("\n", QString::SkipEmptyParts);

    comboBoxBluetooth->clear(); // Clear existing items

    int index = 0;
    for (auto line: lines) {
      if (line.contains("BTH", Qt::CaseInsensitive)) {
        QStringList parts = line.split(" ", QString::SkipEmptyParts);
        if (parts.count() >= 2) {
          QString name = parts[0].trimmed();
          QString address = parts[1].trimmed(); // This might not be an address in all cases
          comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", QString("%1 (%2)").arg(name).arg(
              address).toUtf8().constData()), QVariant(address));
          index++;
        }
      }
    }

    // Optionally, add "none" if no adapters were found
    if (index == 0) {
      comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", "none", nullptr));
    }
  }
#endif
#ifdef Q_OS_MAC
  void SettingsWindow::populateBluetoothComboBoxMac(QComboBox *comboBoxBluetooth) {
    BluetoothAdapterLister lister;
    QStringList adapters = lister.listAdapters();

    comboBoxBluetooth->clear(); // Clear existing items

    if (adapters.isEmpty()) {
      comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", "none", nullptr));
    } else {
      for (const QString &adapter: adapters) {
        QStringList parts = adapter.split(" (");
        if (parts.count() == 2) {
          QString name = parts[0];
          QString address = parts[1].left(parts[1].length() - 1); // Remove trailing ')'
          comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", adapter.toUtf8().constData()),
                                     QVariant(address));
        }
      }
    }
  }
#endif
  void SettingsWindow::populateBluetoothComboBox(QComboBox *comboBoxBluetooth) {
#ifdef Q_OS_LINUX
    populateBluetoothComboBoxLinux(comboBoxBluetooth);
#elif defined Q_OS_WIN
    populateBluetoothComboBoxWindows(comboBoxBluetooth);
#elif defined Q_OS_MAC
    populateBluetoothComboBoxMac(comboBoxBluetooth);
#else
    // Fallback for other platforms
comboBoxBluetooth->clear();
comboBoxBluetooth->addItem("Test");
comboBoxBluetooth->addItem(QCoreApplication::translate("SettingsWindow", "none", nullptr));
#endif
  }

  void SettingsWindow::updateInfo() {
    if (ui_->tab5->isVisible() == true) {
      updateNetworkInfo();
    }
  }

  void SettingsWindow::onSave() {
    if (ui_->radioButtonDriverPositionLeft->isChecked()) {
      configuration_->setDriverPosition(aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_LEFT);
    } else if (ui_->radioButtonDriverPositionCenter->isChecked()) {
      configuration_->setDriverPosition(aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_CENTER);
    } else if (ui_->radioButtonDriverPositionRight->isChecked()) {
      configuration_->setDriverPosition(aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_RIGHT);
    } else if (ui_->radioButtonDriverPositionUnknown->isChecked()) {
      configuration_->setDriverPosition(aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_UNKNOWN);
    }

    configuration_->showClock(ui_->checkBoxShowClock->isChecked());
    configuration_->showBigClock(ui_->checkBoxShowBigClock->isChecked());
    configuration_->oldGUI(ui_->checkBoxOldGUI->isChecked());
    configuration_->setAlphaTrans(static_cast<size_t>(ui_->horizontalSliderAlphaTrans->value()));
    configuration_->hideMenuToggle(ui_->checkBoxHideMenuToggle->isChecked());
    configuration_->showCursor(ui_->checkBoxShowCursor->isChecked());
    configuration_->hideBrightnessControl(ui_->checkBoxHideBrightnessControl->isChecked());
    configuration_->showNetworkinfo(ui_->checkBoxNetworkinfo->isChecked());
    configuration_->hideWarning(ui_->checkBoxDontShowAgain->isChecked());

    configuration_->setDisplayName(ui_->lineEditDisplayName->text().toStdString());
    configuration_->setVehicleMake(ui_->lineEditVehicleMake->text().toStdString());
    configuration_->setVehicleModel(ui_->lineEditVehicleModel->text().toStdString());
    configuration_->setVehicleYear(ui_->lineEditVehicleYear->text().toStdString());
    configuration_->setVehicleID(ui_->lineEditVehicleID->text().toStdString());
    configuration_->setHeadUnitMake(ui_->lineEditHeadUnitMake->text().toStdString());
    configuration_->setHeadUnitModel(ui_->lineEditHeadUnitModel->text().toStdString());
    configuration_->setHeadUnitSoftwareVersion(ui_->lineEditHeadUnitSoftwareVersion->text().toStdString());
    configuration_->setHeadUnitSoftwareBuild(ui_->lineEditHeadUnitSoftwareBuild->text().toStdString());

    configuration_->setVideoFPS(ui_->radioButton30FPS->isChecked()
                                ? aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_30
                                : aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_60);

    if (ui_->radioButton480p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_800x480);
    } else if (ui_->radioButton720p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1280x720);
    } else if (ui_->radioButton1080p->isChecked()) {
      configuration_->setVideoResolution(
          aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1920x1080);
    }

    configuration_->setScreenDPI(static_cast<size_t>(ui_->horizontalSliderScreenDPI->value()));
    configuration_->setOMXLayerIndex(ui_->spinBoxOmxLayerIndex->value());

    QRect videoMargins(0, 0, ui_->spinBoxVideoMarginWidth->value(), ui_->spinBoxVideoMarginHeight->value());
    configuration_->setVideoMargins(std::move(videoMargins));

    configuration_->setTouchscreenEnabled(ui_->checkBoxEnableTouchscreen->isChecked());
    this->saveButtonCheckBoxes();

    if (ui_->comboBoxBluetooth->currentText() == "none") {
      configuration_->setBluetoothAdapterAddress(""); // or any string that indicates no adapter
    } else {
      configuration_->setBluetoothAdapterAddress(
          ui_->comboBoxBluetooth->currentData().toString().toStdString());
    }

    if (ui_->disableProjectionButton->isChecked()) {
        configuration_->setWirelessProjectionEnabled(false);
    } else {
        configuration_->setWirelessProjectionEnabled(true);
    }

    configuration_->setMusicAudioChannelEnabled(ui_->checkBoxMusicAudioChannel->isChecked());
    configuration_->setGuidanceAudioChannelEnabled(ui_->checkBoxSpeechAudioChannel->isChecked());
    //configuration_->setTelephonyAudioChannelEnabled(ui_->checkBoxVoiceAudioChannel->isChecked());
    // TODO: Add CheckBox In
    configuration_->setTelephonyAudioChannelEnabled(true);
    configuration_->setAudioOutputBackendType(
        ui_->radioButtonRtAudio->isChecked() ? configuration::AudioOutputBackendType::RTAUDIO
                                             : configuration::AudioOutputBackendType::QT);

    configuration_->save();

    this->close();
  }

  void SettingsWindow::onResetToDefaults() {
    QMessageBox confirmationMessage(QMessageBox::Question, "Confirmation",
                                    "Are you sure you want to reset settings?",
                                    QMessageBox::Yes | QMessageBox::Cancel);
    //confirmationMessage.setWindowFlags(Qt::WindowStaysOnTopHint);
    if (confirmationMessage.exec() == QMessageBox::Yes) {
      configuration_->reset();
      this->load();
    }
  }

  void SettingsWindow::showEvent(QShowEvent *event) {
    QWidget::showEvent(event);
    this->load();
  }

  void SettingsWindow::load() {
    ui_->radioButtonDriverPositionLeft->setChecked(
        configuration_->getDriverPosition() == aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_LEFT);
    ui_->radioButtonDriverPositionCenter->setChecked(
        configuration_->getDriverPosition() == aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_CENTER);
    ui_->radioButtonDriverPositionRight->setChecked(
        configuration_->getDriverPosition() == aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_RIGHT);
    ui_->radioButtonDriverPositionUnknown->setChecked(
        configuration_->getDriverPosition() == aap_protobuf::service::control::message::DriverPosition::DRIVER_POSITION_UNKNOWN);
    
    ui_->checkBoxShowClock->setChecked(configuration_->showClock());
    ui_->horizontalSliderAlphaTrans->setValue(static_cast<int>(configuration_->getAlphaTrans()));

    ui_->checkBoxShowBigClock->setChecked(configuration_->showBigClock());
    ui_->checkBoxOldGUI->setChecked(configuration_->oldGUI());
    ui_->checkBoxHideMenuToggle->setChecked(configuration_->hideMenuToggle());
    ui_->checkBoxShowCursor->setChecked(configuration_->showCursor());
    ui_->checkBoxHideBrightnessControl->setChecked(configuration_->hideBrightnessControl());
    ui_->checkBoxNetworkinfo->setChecked(configuration_->showNetworkinfo());
    ui_->checkBoxDontShowAgain->setChecked(configuration_->hideWarning());

    ui_->lineEditDisplayName->setText(QString::fromStdString(configuration_->getDisplayName()));
    ui_->lineEditVehicleMake->setText(QString::fromStdString(configuration_->getVehicleMake()));
    ui_->lineEditVehicleModel->setText(QString::fromStdString(configuration_->getVehicleModel()));
    ui_->lineEditVehicleYear->setText(QString::fromStdString(configuration_->getVehicleYear()));
    ui_->lineEditVehicleID->setText(QString::fromStdString(configuration_->getVehicleID()));
    ui_->lineEditHeadUnitMake->setText(QString::fromStdString(configuration_->getHeadUnitMake()));
    ui_->lineEditHeadUnitModel->setText(QString::fromStdString(configuration_->getHeadUnitModel()));
    ui_->lineEditHeadUnitSoftwareVersion->setText(QString::fromStdString(configuration_->getHeadUnitSoftwareVersion()));
    ui_->lineEditHeadUnitSoftwareBuild->setText(QString::fromStdString(configuration_->getHeadUnitSoftwareBuild()));

    ui_->radioButton30FPS->setChecked(configuration_->getVideoFPS() ==
                                      aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_30);
    ui_->radioButton60FPS->setChecked(configuration_->getVideoFPS() ==
                                      aap_protobuf::service::media::sink::message::VideoFrameRateType::VIDEO_FPS_60);

    ui_->radioButton480p->setChecked(configuration_->getVideoResolution() ==
                                     aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_800x480);
    ui_->radioButton720p->setChecked(configuration_->getVideoResolution() ==
                                     aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1280x720);
    ui_->radioButton1080p->setChecked(configuration_->getVideoResolution() ==
                                      aap_protobuf::service::media::sink::message::VideoCodecResolutionType::VIDEO_1920x1080);
    ui_->horizontalSliderScreenDPI->setValue(static_cast<int>(configuration_->getScreenDPI()));
    ui_->spinBoxOmxLayerIndex->setValue(configuration_->getOMXLayerIndex());

    const auto &videoMargins = configuration_->getVideoMargins();
    ui_->spinBoxVideoMarginWidth->setValue(videoMargins.width());
    ui_->spinBoxVideoMarginHeight->setValue(videoMargins.height());

    ui_->checkBoxEnableTouchscreen->setChecked(configuration_->getTouchscreenEnabled());
    this->loadButtonCheckBoxes();

    ui_->disableProjectionButton->setChecked(!configuration_->getWirelessProjectionEnabled());

    ui_->checkBoxMusicAudioChannel->setChecked(configuration_->musicAudioChannelEnabled());
    ui_->checkBoxSpeechAudioChannel->setChecked(configuration_->guidanceAudioChannelEnabled());
    //ui_->telephonyAudioChannelEnabled->setChecked(configuration_->telephonyAudioChannelEnabled());

    const auto &audioOutputBackendType = configuration_->getAudioOutputBackendType();
    ui_->radioButtonRtAudio->setChecked(audioOutputBackendType == configuration::AudioOutputBackendType::RTAUDIO);
    ui_->radioButtonQtAudio->setChecked(audioOutputBackendType == configuration::AudioOutputBackendType::QT);
  }

  void SettingsWindow::loadButtonCheckBoxes() {
    const auto &buttonCodes = configuration_->getButtonCodes();
    ui_->checkBoxPlayButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY) !=
                                        buttonCodes.end());
    ui_->checkBoxPauseButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PAUSE) !=
                                         buttonCodes.end());
    ui_->checkBoxTogglePlayButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                        aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY_PAUSE) !=
                                              buttonCodes.end());
    ui_->checkBoxNextTrackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                       aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_NEXT) !=
                                             buttonCodes.end());
    ui_->checkBoxPreviousTrackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                           aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PREVIOUS) !=
                                                 buttonCodes.end());
    ui_->checkBoxHomeButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_HOME) !=
                                        buttonCodes.end());
    ui_->checkBoxPhoneButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_CALL) !=
                                         buttonCodes.end());
    ui_->checkBoxCallEndButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                     aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ENDCALL) !=
                                           buttonCodes.end());
    ui_->checkBoxVoiceCommandButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                          aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_SEARCH) !=
                                                buttonCodes.end());
    ui_->checkBoxLeftButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_LEFT) !=
                                        buttonCodes.end());
    ui_->checkBoxRightButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_RIGHT) !=
                                         buttonCodes.end());
    ui_->checkBoxUpButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_UP) !=
                                      buttonCodes.end());
    ui_->checkBoxDownButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_DOWN) !=
                                        buttonCodes.end());
    ui_->checkBoxScrollWheelButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                         aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ROTARY_CONTROLLER) !=
                                               buttonCodes.end());
    ui_->checkBoxBackButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                  aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_BACK) !=
                                        buttonCodes.end());
    ui_->checkBoxEnterButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                   aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_CENTER) !=
                                         buttonCodes.end());
    ui_->checkBoxNavButton->setChecked(std::find(buttonCodes.begin(), buttonCodes.end(),
                                                 aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_NAVIGATION) !=
                                       buttonCodes.end());
  }

  void SettingsWindow::setButtonCheckBoxes(bool value) {
    ui_->checkBoxPlayButton->setChecked(value);
    ui_->checkBoxPauseButton->setChecked(value);
    ui_->checkBoxTogglePlayButton->setChecked(value);
    ui_->checkBoxNextTrackButton->setChecked(value);
    ui_->checkBoxPreviousTrackButton->setChecked(value);
    ui_->checkBoxHomeButton->setChecked(value);
    ui_->checkBoxPhoneButton->setChecked(value);
    ui_->checkBoxCallEndButton->setChecked(value);
    ui_->checkBoxVoiceCommandButton->setChecked(value);
    ui_->checkBoxLeftButton->setChecked(value);
    ui_->checkBoxRightButton->setChecked(value);
    ui_->checkBoxUpButton->setChecked(value);
    ui_->checkBoxDownButton->setChecked(value);
    ui_->checkBoxScrollWheelButton->setChecked(value);
    ui_->checkBoxBackButton->setChecked(value);
    ui_->checkBoxEnterButton->setChecked(value);
    ui_->checkBoxNavButton->setChecked(value);
  }

  void SettingsWindow::saveButtonCheckBoxes() {
    configuration::IConfiguration::ButtonCodes buttonCodes;
    this->saveButtonCheckBox(ui_->checkBoxPlayButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY);
    this->saveButtonCheckBox(ui_->checkBoxPauseButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PAUSE);
    this->saveButtonCheckBox(ui_->checkBoxTogglePlayButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PLAY_PAUSE);
    this->saveButtonCheckBox(ui_->checkBoxNextTrackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_NEXT);
    this->saveButtonCheckBox(ui_->checkBoxPreviousTrackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_MEDIA_PREVIOUS);
    this->saveButtonCheckBox(ui_->checkBoxHomeButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_HOME);
    this->saveButtonCheckBox(ui_->checkBoxPhoneButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_CALL);
    this->saveButtonCheckBox(ui_->checkBoxCallEndButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ENDCALL);
    this->saveButtonCheckBox(ui_->checkBoxVoiceCommandButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_SEARCH);
    this->saveButtonCheckBox(ui_->checkBoxLeftButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_LEFT);
    this->saveButtonCheckBox(ui_->checkBoxRightButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_RIGHT);
    this->saveButtonCheckBox(ui_->checkBoxUpButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_UP);
    this->saveButtonCheckBox(ui_->checkBoxDownButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_DOWN);
    this->saveButtonCheckBox(ui_->checkBoxScrollWheelButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_ROTARY_CONTROLLER);
    this->saveButtonCheckBox(ui_->checkBoxBackButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_BACK);
    this->saveButtonCheckBox(ui_->checkBoxEnterButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_DPAD_CENTER);
    this->saveButtonCheckBox(ui_->checkBoxNavButton, buttonCodes,
                             aap_protobuf::service::media::sink::message::KeyCode::KEYCODE_NAVIGATION);
    configuration_->setButtonCodes(buttonCodes);
  }

  void SettingsWindow::saveButtonCheckBox(const QCheckBox *checkBox,
                                          configuration::IConfiguration::ButtonCodes &buttonCodes,
                                          aap_protobuf::service::media::sink::message::KeyCode buttonCode) {
    if (checkBox->isChecked()) {
      buttonCodes.push_back(buttonCode);
    }
  }

  void SettingsWindow::onUpdateScreenDPI(int value) {
    ui_->labelScreenDPIValue->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateAlphaTrans(int value) {
    double alpha = value / 100.0;
    ui_->labelAlphaTransValue->setText(QString::number(alpha));
  }

  void SettingsWindow::onUpdateBrightnessDay(int value) {
    ui_->labelBrightnessDay->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateBrightnessNight(int value) {
    ui_->labelBrightnessNight->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateSystemVolume(int value) {
    ui_->labelSystemVolumeValue->setText(QString::number(value));
  }

  void SettingsWindow::onUpdateSystemCapture(int value) {
    ui_->labelSystemCaptureValue->setText(QString::number(value));
  }

  void SettingsWindow::unpairAll() {
    system("/usr/local/bin/crankshaft bluetooth unpair &");
  }

  void SettingsWindow::loadSystemValues() {
    // set brightness slider attribs
    ui_->horizontalSliderDay->setMinimum(configuration_->getCSValue("BR_MIN").toInt());
    ui_->horizontalSliderDay->setMaximum(configuration_->getCSValue("BR_MAX").toInt());
    ui_->horizontalSliderDay->setSingleStep(configuration_->getCSValue("BR_STEP").toInt());
    ui_->horizontalSliderDay->setTickInterval(configuration_->getCSValue("BR_STEP").toInt());
    ui_->horizontalSliderDay->setValue(configuration_->getCSValue("BR_DAY").toInt());

    ui_->horizontalSliderNight->setMinimum(configuration_->getCSValue("BR_MIN").toInt());
    ui_->horizontalSliderNight->setMaximum(configuration_->getCSValue("BR_MAX").toInt());
    ui_->horizontalSliderNight->setSingleStep(configuration_->getCSValue("BR_STEP").toInt());
    ui_->horizontalSliderNight->setTickInterval(configuration_->getCSValue("BR_STEP").toInt());
    ui_->horizontalSliderNight->setValue(configuration_->getCSValue("BR_NIGHT").toInt());

    if (std::ifstream("/tmp/return_value")) {
      QString return_values = configuration_->readFileContent("/tmp/return_value");
      QStringList getparams = return_values.split("#");

      // set volume
      ui_->labelSystemVolumeValue->setText(configuration_->readFileContent("/boot/crankshaft/volume"));
      ui_->horizontalSliderSystemVolume->setValue(
          configuration_->readFileContent("/boot/crankshaft/volume").toInt());
      // set cap volume
      ui_->labelSystemCaptureValue->setText(configuration_->readFileContent("/boot/crankshaft/capvolume"));
      ui_->horizontalSliderSystemCapture->setValue(
          configuration_->readFileContent("/boot/crankshaft/capvolume").toInt());

      populateBluetoothComboBox(ui_->comboBoxBluetooth);

      if (std::ifstream("/tmp/get_inputs")) {
        QFile inputsFile(QString("/tmp/get_inputs"));
        inputsFile.open(QIODevice::ReadOnly);
        QTextStream data_return(&inputsFile);
        QStringList inputs = data_return.readAll().split("\n");
        inputsFile.close();
        int cleaner = ui_->comboBoxPulseInput->count();
        while (cleaner > -1) {
          ui_->comboBoxPulseInput->removeItem(cleaner);
          cleaner--;
        }
        int indexin = inputs.count();
        int countin = 0;
        while (countin < indexin - 1) {
          ui_->comboBoxPulseInput->addItem(inputs[countin]);
          countin++;
        }
      }

      if (std::ifstream("/tmp/get_outputs")) {
        QFile outputsFile(QString("/tmp/get_outputs"));
        outputsFile.open(QIODevice::ReadOnly);
        QTextStream data_return(&outputsFile);
        QStringList outputs = data_return.readAll().split("\n");
        outputsFile.close();
        int cleaner = ui_->comboBoxPulseOutput->count();
        while (cleaner > -1) {
          ui_->comboBoxPulseOutput->removeItem(cleaner);
          cleaner--;
        }
        int indexout = outputs.count();
        int countout = 0;
        while (countout < indexout - 1) {
          ui_->comboBoxPulseOutput->addItem(outputs[countout]);
          countout++;
        }
      }

      ui_->comboBoxPulseOutput->setCurrentText(configuration_->readFileContent("/tmp/get_default_output"));
      ui_->comboBoxPulseInput->setCurrentText(configuration_->readFileContent("/tmp/get_default_input"));

      // Wifi Hotspot
      if (configuration_->getCSValue("ENABLE_HOTSPOT") == "1") {
        ui_->checkBoxHotspot->setChecked(true);
      } else {
        ui_->checkBoxHotspot->setChecked(false);
      }

      if (configuration_->getCSValue("ENABLE_PAIRABLE") == "1") {
        ui_->checkBoxBluetoothAutoPair->setChecked(true);
      } else {
        ui_->checkBoxBluetoothAutoPair->setChecked(false);
      }
      // set bluetooth type
      if (configuration_->getCSValue("ENABLE_BLUETOOTH") == "1") {
        QString bt = configuration_->getParamFromFile("/boot/config.txt", "dtoverlay=pi3-disable-bt");

        QString selectedAddress = QString::fromStdString(
            configuration_->getBluetoothAdapterAddress());  //.value("BluetoothAdapterAddress", "none").toString();

        // Iterate through the items to find the one with the matching data
        bool found = false;
        for (int i = 0; i < ui_->comboBoxBluetooth->count(); ++i) {
          if (ui_->comboBoxBluetooth->itemData(i).toString() == selectedAddress) {
            ui_->comboBoxBluetooth->setCurrentIndex(i);
            found = true;
            break;
          }
        }

        if (!found) {
          ui_->comboBoxBluetooth->setCurrentIndex(ui_->comboBoxBluetooth->findText("none"));
        }
      } else {
        ui_->comboBoxBluetooth->setCurrentText("none");
      }


      // wifi country code
      ui_->comboBoxCountryCode->setCurrentIndex(
          ui_->comboBoxCountryCode->findText(configuration_->getCSValue("WIFI_COUNTRY"),
                                             Qt::MatchFlag::MatchStartsWith));
    }
    // update network info
    updateNetworkInfo();
  }

  void SettingsWindow::onStartHotspot() {
    ui_->label_modeswitchprogress->setText("Wait ...");
    ui_->clientNetworkSelect->hide();
    ui_->label_notavailable->show();
    ui_->radioButtonClient->setEnabled(0);
    ui_->radioButtonHotspot->setEnabled(0);
    ui_->lineEdit_wlan0->setText("");
    ui_->lineEditWifiSSID->setText("");
    ui_->pushButtonNetworkAuto->hide();
    qApp->processEvents();
    std::remove("/tmp/manual_hotspot_control");
    std::ofstream("/tmp/manual_hotspot_control");
    system("/opt/crankshaft/service_hotspot.sh start &");
  }

  void SettingsWindow::onStopHotspot() {
    ui_->label_modeswitchprogress->setText("Wait ...");
    ui_->clientNetworkSelect->hide();
    ui_->label_notavailable->show();
    ui_->radioButtonClient->setEnabled(0);
    ui_->radioButtonHotspot->setEnabled(0);
    ui_->lineEdit_wlan0->setText("");
    ui_->lineEditWifiSSID->setText("");
    ui_->lineEditPassword->setText("");
    ui_->pushButtonNetworkAuto->hide();
    qApp->processEvents();
    system("/opt/crankshaft/service_hotspot.sh stop &");
  }

#ifdef MAC_OS

  void SettingsWindow::getMacMemoryInfo(QString &freeMemory) {
    mach_port_t host_port;
    vm_size_t page_size;
    vm_statistics64_data_t vm_stats;

    host_port = mach_host_self();
    mach_msg_type_number_t count = HOST_VM_INFO64_COUNT;
    host_page_size(host_port, &page_size);
    if (host_statistics64(host_port, HOST_VM_INFO64, (host_info64_t) &vm_stats, &count) != KERN_SUCCESS) {
      freeMemory = "Error in getting memory info";
      return;
    }

    natural_t free_count = vm_stats.free_count;
    uint64_t free_memory = (uint64_t) free_count * (uint64_t) page_size;
    freeMemory = QString::number(free_memory / (1024 * 1024)) + " MB";
  }

#endif

  void SettingsWindow::show_tab1() {
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();
    ui_->tab1->show();
  }

  void SettingsWindow::show_tab2() {
    ui_->tab1->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();
    ui_->tab2->show();
  }

  void SettingsWindow::show_tab3() {
    ui_->tab1->hide();
    ui_->tab2->hide();
    ui_->tab4->hide();
    ui_->tab5->hide();
    ui_->tab3->show();
  }

  void SettingsWindow::show_tab4() {
    ui_->tab1->hide();
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab5->hide();
    ui_->tab4->show();
  }

  void SettingsWindow::show_tab5() {
    ui_->tab1->hide();
    ui_->tab2->hide();
    ui_->tab3->hide();
    ui_->tab4->hide();
    ui_->tab5->show();
  }

}


void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonAudioTest_clicked() {
  ui_->labelTestInProgress->show();
  ui_->pushButtonAudioTest->hide();
  qApp->processEvents();
  system("/usr/local/bin/crankshaft audio test");
  ui_->pushButtonAudioTest->show();
  ui_->labelTestInProgress->hide();
}

void f1x::openauto::autoapp::ui::SettingsWindow::updateNetworkInfo() {
  if (std::ifstream("/tmp/samba_running")) {
    ui_->labelSambaStatus->setText("running");
    if (ui_->pushButtonSambaStart->isVisible() == true) {
      ui_->pushButtonSambaStart->hide();
      ui_->pushButtonSambaStop->show();
    }
  } else {
    ui_->labelSambaStatus->setText("stopped");
    if (ui_->pushButtonSambaStop->isVisible() == true) {
      ui_->pushButtonSambaStop->hide();
      ui_->pushButtonSambaStart->show();
    }
  }

  if (!std::ifstream("/tmp/mode_change_progress")) {
    QNetworkInterface eth0if = QNetworkInterface::interfaceFromName("eth0");
    if (eth0if.flags().testFlag(QNetworkInterface::IsUp)) {
      QList<QNetworkAddressEntry> entrieseth0 = eth0if.addressEntries();
      if (!entrieseth0.isEmpty()) {
        QNetworkAddressEntry eth0 = entrieseth0.first();
        //qDebug() << "eth0: " << eth0.ip();
        ui_->lineEdit_eth0->setText(eth0.ip().toString());
      }
    } else {
      //qDebug() << "eth0: down";
      ui_->lineEdit_eth0->setText("interface down");
    }

    QNetworkInterface wlan0if = QNetworkInterface::interfaceFromName("wlan0");
    if (wlan0if.flags().testFlag(QNetworkInterface::IsUp)) {
      QList<QNetworkAddressEntry> entrieswlan0 = wlan0if.addressEntries();
      if (!entrieswlan0.isEmpty()) {
        QNetworkAddressEntry wlan0 = entrieswlan0.first();
        //qDebug() << "wlan0: " << wlan0.ip();
        ui_->lineEdit_wlan0->setText(wlan0.ip().toString());
      }
    } else {
      //qDebug() << "wlan0: down";
      ui_->lineEdit_wlan0->setText("interface down");
    }

    if (std::ifstream("/tmp/hotspot_active")) {
      ui_->radioButtonClient->setEnabled(1);
      ui_->radioButtonHotspot->setEnabled(1);
      ui_->radioButtonHotspot->setChecked(1);
      ui_->radioButtonClient->setChecked(0);
      ui_->label_modeswitchprogress->setText("Ok");
      ui_->lineEditWifiSSID->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "ssid"));
      ui_->lineEditPassword->show();
      ui_->label_password->show();
      ui_->lineEditPassword->setText(configuration_->getParamFromFile("/etc/hostapd/hostapd.conf", "wpa_passphrase"));
      ui_->clientNetworkSelect->hide();
      ui_->pushButtonNetworkAuto->hide();
      ui_->label_notavailable->show();
    } else {
      ui_->radioButtonClient->setEnabled(1);
      ui_->radioButtonHotspot->setEnabled(1);
      ui_->radioButtonHotspot->setChecked(0);
      ui_->radioButtonClient->setChecked(1);
      ui_->label_modeswitchprogress->setText("Ok");
      ui_->lineEditWifiSSID->setText(configuration_->readFileContent("/tmp/wifi_ssid"));
      ui_->lineEditPassword->hide();
      ui_->label_password->hide();
      ui_->lineEditPassword->setText("");
      ui_->clientNetworkSelect->show();
      ui_->label_notavailable->hide();
      ui_->pushButtonNetworkAuto->show();

      if (!std::ifstream("/boot/crankshaft/network1.conf")) {
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetwork0->show();
      }
      if (!std::ifstream("/boot/crankshaft/network0.conf")) {
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetwork0->setText(configuration_->getCSValue("WIFI2_SSID"));
      }
      if (!std::ifstream("/boot/crankshaft/network0.conf") && !std::ifstream("/boot/crankshaft/network1.conf")) {
        ui_->pushButtonNetwork0->hide();
        ui_->pushButtonNetwork1->hide();
        ui_->pushButtonNetworkAuto->hide();
        ui_->label_notavailable->show();
      }
    }
  }
}

void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonNetwork0_clicked() {
  ui_->lineEdit_wlan0->setText("");
  ui_->lineEditWifiSSID->setText("");
  ui_->lineEditPassword->setText("");
  qApp->processEvents();
  system("/usr/local/bin/crankshaft network 0 >/dev/null 2>&1 &");

}

void f1x::openauto::autoapp::ui::SettingsWindow::on_pushButtonNetwork1_clicked() {
  ui_->lineEdit_wlan0->setText("");
  ui_->lineEditWifiSSID->setText("");
  ui_->lineEditPassword->setText("");
  qApp->processEvents();
  system("/usr/local/bin/crankshaft network 1 >/dev/null 2>&1 &");
}

void f1x::openauto::autoapp::ui::SettingsWindow::keyPressEvent(QKeyEvent *event) {
  if (event->key() == Qt::Key_Escape) {
    f1x::openauto::autoapp::ui::SettingsWindow::close();
  }
  if (event->key() == Qt::Key_Return) {
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyPress, Qt::Key_Space, Qt::NoModifier));
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyRelease, Qt::Key_Space, Qt::NoModifier));
  }
  if (event->key() == Qt::Key_1) {
    QApplication::postEvent(QApplication::focusWidget(),
                            new QKeyEvent(QEvent::KeyPress, Qt::Key_Tab, Qt::ShiftModifier));
  }
  if (event->key() == Qt::Key_2) {
    QApplication::postEvent(QApplication::focusWidget(), new QKeyEvent(QEvent::KeyPress, Qt::Key_Tab, Qt::NoModifier));
  }
}
